### ISSUE TITLE
Store design requirements analyses?

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#122]
It might be worth preserving discussions regarding design requirements (or character sets – what is included and why), see #118 for example, next to the data as they contain valuable reasoning that might get lost here in issues. Notably, the discussions might be expanded with time as orthographies get update or new solutions occur to us while the design requirements should contain (imho) a succinct and most recent recommendation.

These discussions could be saved in a separate file should we decided to save language data in individual folders as per #121 .

**Comment by kontur** [comment]
I think we could simple refer to the github issue by URL in a note or design requirement, since that facilitates discussion and shows track record; assuming these discussions happened in github issues—those that didn't could be included as resolved stub issue with the otherwise obtained information.

**Comment by MrBrezina** [comment]
Agreed. We will just need to be cautious if moving the data from GitHub in the future.
