### ISSUE TITLE
Fixes for jbo

### ISSUE THREAD

**Issue by berrymot** [rosettatype/hyperglot#140]
Lojban 'officially' uses `'.,abcdefgiklmnoprstuvxyz` as lowercase and `ABCDEFGIJKLMNOPRSTUVXYZ` as capital (for marking stress in names). Note the lack of h/q/w. Sometimes `h` is used for `'` in software that does not treat the apostrophe as a letter.

source: [CLL](https://lojban.org/publications/cll/cll_v1.1_xhtml-section-chunks/chapter-phonology.html#section-orthography), the official Lojban book

**Comment by berrymot** [comment]
(to clarify: yes period and comma are letters)

**Comment by kontur** [comment]
Thank you, those corrections will be included in the next release. I've added `'` as unicode `U+0027` _plain_ APOSTROPHE, as opposed to `ʼ` `U+02BC` "MODIFIER LETTER APOSTROPHE", since the CLL seems to talk about following "ASCII ordering" for the orthography which implies the use of `U+0027` even though `U+02BC` might be more letter like.

This seems like another case for #82 regarding the apostrophe; both or several unicode points seem valid.
