### ISSUE TITLE
Feedback regarding the new web app

### ISSUE THREAD

**Issue by MrBrezina** [rosettatype/hyperglot#142]
We have soft-launched a new version of the Hyperglot web app (faster, nicer, more useful). If you have any comments, let us know here, but don’t make us cry.

The website is here: https://hyperglot.rosettatype.com 

Thank you!

**Comment by punchcutter** [comment]
One thing that immediately caught my eye that Chakma (and I assume any other SMP Unicode) is being displayed as UTF-16 pairs instead of the expected SMP codepoints. For example U+11107 is shown like

![image](https://github.com/rosettatype/hyperglot/assets/11257204/2f949dc4-d303-407e-8b2c-56a00cde4b71)

This also affect the overview where every single character says "multiple" instead of showing the expected codepoints...

![image](https://github.com/rosettatype/hyperglot/assets/11257204/e6086741-6d58-4e42-bb01-472b88bfd55c)

**Comment by moyogo** [comment]
Some deisgn requirements notes are the same but slightly different.
<img width="786" alt="Screenshot 2023-11-25 at 06 29 14" src="https://github.com/rosettatype/hyperglot/assets/1923747/a2d1c7bd-5680-4bfa-b245-fbee6518610f">

The one for Ŋ can be the same all the time #143.

**Comment by kontur** [comment]
Both issues fixed. The UFT16 unicode fix is live on the web app, the cleaned up descriptions will come to the app with the next release of the hyperglot lib.

**Comment by kontur** [comment]
Closing this now as the launch of the new version has been a while ago. Thanks for all reported issues, feel free to open specific issues should you notice something.
