### ISSUE TITLE
KeyError: 'post' on some fonts that have the 'post' table

### ISSUE THREAD

**Issue by cjchapman** [rosettatype/hyperglot#24]
I see crashes on some fonts (e.g. some of the Noto Fonts) with `KeyError: post`, e.g:
```
$ hyperglot NotoSansMalayalam-Regular.ttf 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 372, in __getitem__
    return self.tables[tag]
KeyError: 'post'
```
…even though the fonts in question have the post table, e.g.:
```
>>> font = TTFont('NotoSansMalayalam-Regular.ttf')
>>> font.keys()
['GlyphOrder', 'head', 'hhea', 'maxp', 'OS/2', 'hmtx', 'cmap', 'loca', 'glyf', 'name', 'post', 'gasp', 'GDEF', 'GPOS', 'GSUB']
```

**Comment by kontur** [comment]
Could it be this is an outdated or _manipulated_ version of the font file?

Testing with this [NotoSansMalayalam-Regular.ttf](https://github.com/googlefonts/noto-fonts/blob/dcd8521fee773d89ca19d4c2c266b2f5dbe88395/hinted/ttf/NotoSansMalayalam/NotoSansMalayalam-Regular.ttf) I get:

```
$ hyperglot ~/Desktop/NotoSansMalayalam-Regular.ttf 

===================================================
NotoSansMalayalam-Regular.ttf has base support for:
===================================================


1 language of Malayalam script:
-------------------------------
Malayalam

1 languages supported in total.
```

Feel free to attach your particular version of the font here and I'm happy to test with that. By the looks of the error, however, it seems like a fontTools problem relating to simply parsing the font. The Hyperglot CLI does not much else in fontTools than read in the `cmap` table, so no specific interaction with the `post` table at all.

**Comment by cjchapman** [comment]
It might well be out of date.  Here's the version I was using:
[NotoSansMalayalam-Regular.ttf.zip](https://github.com/rosettatype/hyperglot/files/6213105/NotoSansMalayalam-Regular.ttf.zip)

**Comment by cjchapman** [comment]
The version I posted above is the 1.04 unhinted version and the version you pointed to is the 2.001 hinted version of Noto Sans Malayalam. So, yes, out of date.  However, I'm able to reproduce this `KeyError` even with fonts in my macOS Library/Fonts folder, e.g.:
```bash
$ hyperglot /Library/Fonts/Arial\ Unicode.ttf 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 372, in __getitem__
    return self.tables[tag]
KeyError: 'post'
```

**Comment by MrBrezina** [comment]
What is your version of fontTools?

**Comment by cjchapman** [comment]
```bash
$ pip3 freeze  | egrep "(fonttools|hyperglot)"
fonttools==4.21.1
hyperglot==0.2.9
```

**Comment by cjchapman** [comment]
I tried it again just now with the latest `hyperglot`:
```bash
$ pip3 freeze | egrep "(fonttools|hyperglot)"
fonttools==4.21.1
hyperglot==0.2.11
$ hyperglot /Library/Fonts/Arial\ Unicode.ttf 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 372, in __getitem__
    return self.tables[tag]
KeyError: 'post'
```

**Comment by kontur** [comment]
I'm inclined to escalate this to fontTools. Could you do two things:

- in case you previously just updated hyperglot, try explicitly pip uninstall fonttools and hyperglot, and confirm both are in fact uninstalled (e.g. both `ttx somefont.ttf` and `hyperglot somefont.ttf` should complain about not finding that command), then reinstall hyperglot
- even better would be to test in a new python virtual environment, if you are familiar with how to do this (in _very short_: `pip install virtualenv` & `python -m virtualenv freshenvironment` & `source freshenvironment/bin/activate` and then `pip install hyperglot` and then test `hyperglot somefont.ttf`)
- confirm if this happens for all fonts, or if there are in fact some fonts it does not happen with (ideally we'd have such a case with a font file that is openly accessible for testing for one that fails and one that works — but if _all_ fonts fail that is a finding in itself, too)

Hyperglot uses fontTools for two very, very minor things only:

Checking a font can in fact be parsed in fontTools; this does not seem to be the root of your error, since it would exit the CLI command with the error message.

```
try:
            _font = TTFont(v, lazy=True)
            _font.close()
        except Exception as e:
            raise click.BadParameter("Could not convert TTFont from passed in "
                                     "font file (%s)" % str(e))
```

And then actually getting the unicode points in the font:

```
def parse_font_chars(path):
    """
    Open the provided font path and extract the codepoints encoded in the font
    @return list of characters
    """
    font = TTFont(path, lazy=True)
    cmap = font["cmap"]
    font.close()

    # The cmap keys are int codepoints
    return [chr(c) for c in cmap.getBestCmap().keys()]
```

Neither of these two instances of fontTools use does anything besides reading in the font, and accessing some basic parts of its contents.

As per my above suggestion, the only thing I could imagine is that some outdated version of fontTools lurks somewhere and is causing the issue, or otherwise this is something very specific to your machine, in which case I'd refer this to fontTools to figure out.

**Comment by kontur** [comment]
Super, thanks for digging deeper into this. Yes, that makes sense. I should have stored the result of `getBestCmap()`, not the cmap table, before closing the font; or not closed the font explicitly at all.

Will ship a fix for this in the next update 👍

**Comment by cjchapman** [comment]
You're welcome. 😀
