### ISSUE TITLE
Ter Sami (sjt)

### ISSUE THREAD

**Issue by meehkal** [rosettatype/hyperglot#34]
This language has no orthography and is not written. In the scientific literature, sometimes, one small booklet of poems by Oktyabrina Voronova (1934–1990) is mentioned as having been written in Ter Sami. But the orthography used there is similar to Kildin Sami.

**Comment by kontur** [comment]
Thanks for the pointer. This might be a case where we opt to go with the [guideline from the README](https://github.com/rosettatype/hyperglot/blob/master/README_database.md#contribution-notes):

> Languages that are not written should not be included.

@MrBrezina we could have this with a `transliteration` orthography, or maybe we want to eventually also list such languages for other reasons.

@meehkal although not written, is this a language that has speakers and is "alive"? How does the orthography differ from Kildin Sami?

**Comment by meehkal** [comment]
@kontur 1) The orthography used in the mentioned booklet is completely similar to Kildin Saami (but uses Ӹ a lot, which normally is not part of the Kildin alphabet, although some Kildin Saami writers sometimes use it too). By the way, in addition to the alphabet (i.e. set of letters), even the morphophonological rules and the vocabulary in this booklet are basically similar to Kildin Saami. At best, this booklet represents a dialectal variant of Kildin Saami. 
@kontur 2) There are perhaps 5-10 speakers alive; nobody writes in the language, to what I have seen. 

@MrBrezina Could we perhaps keep the language in the inventory, but somehow linked to Kildin, like a variant? Note also that earlier researchers (e.g. T. I. Itkonen 1958. "Wörterbuch des Kolta- und Kolalappischen" Helsinki) use "Kola Sami" as the overall name for collecting all Kildin Sami and Ter Sami dialects (and distinguishing it from Skolt Sami (sms) ["Koltalappisch" means "Skolt Sami" in the title of the mentioned dictionary]).

**Comment by MrBrezina** [comment]
@meehkal How about we include the orthography as inherited from Kildin Sami and mark it `status: secondary ` and add a note about its use in this particular book? It is a nice way to bring attention to endangered languages, imho.

About the different structure of languages and dialects. We want to adhere to ISO as much as possible (only changing the language names if they are derogatory or otherwise substantially wrong). Same for the scripts. We could add a note to Kildin and Ter Sami saying something like:
“Klidin and Ter Sami languages are grouped together as Kola Sami by some linguists.”. That way, it will be searchable as Kola Sami at some point. I added something similar to Romanian being called Moldavian when used in Moldavia.

**Comment by MrBrezina** [comment]
We need to decide whether our objective is:
- to have it in the database --> `status: secondary`
- to have it match during detection --> `status: primary`

**Comment by sergiolmartins** [comment]
I would prefer to opt for @MrBrezina's suggestion, regarding considering Ter Sami a dialect. I am rather wary of deviating from the ISO categorisation, without a seriously strong argument for it.

If it's not written and we're keeping it in the database, shouldn't we expand that criteria to other non-written languages? If we're keeping it in the database, I think `status: secondary` is probably best, not due to the fact that it has few speakers but due to not having (much) written representation, which is the whole purpose of the database. However adding a note mentioning that it's nearly extinct would be good.

**Comment by meehkal** [comment]
>     * to have it in the database --> `status: secondary`

I suggest this solution, too. Plus additionally notes like: a) "Ter Saami has been used as a written language only in very few texts." b) "Currently, the number of active speakers of Ter Saami is likely lower than 10." c) “Kildin and Ter Sami languages are grouped together as Kola Sami by some linguists.”

**Comment by kontur** [comment]
Changing `sjt` to inherit from Kildin Sami (I add `Ӹ` as overwrite specific to the `auxiliary` of `ter`, and the orthography status is marked `secondary`. Thanks for your insight @meehkal
