### ISSUE TITLE
Pite Sami (sje)

### ISSUE THREAD

**Issue by meehkal** [rosettatype/hyperglot#43]
What are these letters?

> ’ \ '

What source is used for this language?

@jeutzsch, what do you think?

**Comment by jeutzsch** [comment]
I'd be happy to help with Pite Saami (sje), but I don't really understand these two questions, perhaps because I'm not very familiar with hyperglot.
If you are looking for a source to cite for the officially recognized orthography, then unfortunately to my knowledge there is no good source available except for a [downloadable file](https://assets.ctfassets.net/kkxfrpcp7iyu/3Wcbuu6rq0QKdtFk5ZF4UE/85f4d457d87f4997ef59ef72232a4a42/Bidums__megiella_tj__llemvuohke.pdf) which is linked to at the end of [this North Saami blog entry](http://www.giella.org/articles/6YKrmI8lbgWVUc6KS7dyKp). Otherwise, I maintain [this website](http://saami.uni-freiburg.de/psdp/stavningsregler/main.php) in Swedish which presents the orthographic rules, but it is nothing "official" (as in, nothing produced or supported by any relevant (Pite-)Saami political or legal authority).

**Comment by sergiolmartins** [comment]
@meehkal I'm pretty sure those are a mistake, probably a ctrl+c/ctrl+v fail. I see no reason for them to be part of the base. Omniglot and _A grammar of Pite Saami_ were the sources most used.

**Comment by kontur** [comment]
Same as #45 .

I'll do a full review of any presence of `\` in the data to see if there are other such unintended escape sequences. Even orthographies that require a `"` or `'` should use other encoded forms, and not the "dumb quotes" — which also conflict with yaml and cause the issue at hand.

**Comment by kontur** [comment]
Resolved, thanks for highlighting this.
