### ISSUE TITLE
Skolt Sami (sms)

### ISSUE THREAD

**Issue by meehkal** [rosettatype/hyperglot#45]
Modifier letter vertical line (ˈ) is not a letter, strictly speaking. It marks an overlong consonant, e.g. nˈn (as opposed to long nn), but is normally used only for didactic purposes, e.g. in teaching materials.

**Comment by meehkal** [comment]
Combining dot below (U+0323) is another "didactic mark" in Skolt Sami. It is used with a few vowels to mark an underlying morphophonological property of diphthongs, e.g. <uẹ> versus <ue>, but only in teaching materials, dictionaries, etc.

**Comment by kontur** [comment]
In the base orthography for sje (`A B D E F G H I J K L M N O P R S T U V Á Ä Å Đ Ŋ Ŧ a b d e f g h i j k l m n o p r s t u v á ä å đ ŋ ŧ ’ \ '`) I am almost certain the last two are an escape sequence for `'`, which is due to yaml not allowing `'` as such, and needs to be written as `\'` — however, I wonder if the presence of the plain `'` is an error to begin with and is some kind of input error / "ASCII" form of the included _acutegravecomb_ `’`. 

I'd opt to remove the last two.

**Comment by kontur** [comment]
I've replace the "single quote" with modifier letter apostrophe. We will refine the handling of marks in just a bit, and I will add `Modifier letter vertical line (ˈ)` and `Combining dot below (U+0323)` as "auxiliary" marks then, or otherwise note them. They should not be part of the base orthography used for checking font support if their use is only circumstantial.

**Comment by kontur** [comment]
Depends on #28

**Comment by kontur** [comment]
This is in an of itself resolved, but #47 might affect this language, too, if there is any kind of generalisation possible.
