### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by simoncozens** [rosettatype/hyperglot#99]
Hello! Thank you for Hyperglot - it's a very useful resource. But I am a bit confused about where the data comes from and how it is licensed:

* There is a GPL3 license in the repository. This implies it covers the whole repository, code and data.
* The "main language data set" is credited to David Březina in the authors/contributors list, but the "sources" of many orthographies in the data file are given as "Wikipedia" and "Omniglot"
* Omniglot is copyright, but provides a [grant of use](https://www.omniglot.com/faqs.htm#use).
* Wikipedia is Creative Commons SA, meaning that any derived work is meant to be licensed under the same CC-SA license.

Could you clarify what the license terms of the database are?

**Comment by MrBrezina** [comment]
Hi Simon,

glad to see you are interested in Hyperglot. I don’t think there is a problem as orthographies, language names, population data can be considered facts (or ideas depending on your philosophical preferences) and as such they cannot be copyrighted. We did not reuse any particular expression of the information, e.g. copied an article or format in which those facts are presented.

The references are provided in an academic sense to support provenance and allow follow up in case more information is needed.

Our database is now distributed under GNU v3.0, but we are happy to consider other open source alternatives.

**Comment by simoncozens** [comment]
If you're saying that the database is purely factual (which I think I agree with), I'm not sure that you can also say that it you require its users to follow the terms of the GPLv3. I suspect the right approach is to put the *code* under GPLv3 but the database into the public domain. But I am not a license expert.

This is a problem for open source tools built on top of hyperglot, since the GPL requires any work which uses GPL libraries such as hyperglot to [also be released under the GPL](https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL).

**Comment by MrBrezina** [comment]
Mmm. the data is not, but the database might be (structure etc.), but I think your proposed approach is sound.

I think @davelab6 mentioned this as well. Maybe he will have a suggestion. I will come back to you on this.

**Comment by davelab6** [comment]
There's also in the EU, IIRC, "database rights" which are different from regular copyrights and cover specific curations of what are, in isolation, public domain, facts, as you say. From https://wiki.creativecommons.org/wiki/ShareAlike_compatibility_analysis:_GPL I believe CC-BY-SA covers those rights in addition to standard copyrights.

I believe any reuse of CC-BY-SA content requires the result to by CC-BY-SA, with the sole exception that the original parts remain CC-BY-SA but can be combined with new parts under GPLv3, and other parts also GPLv3-compatible (including Apache 2). 

So, I think its fair to conclude the hyperglot code **and database** are GPLv3.

> Omniglot is copyright, but provides a [grant of use](https://www.omniglot.com/faqs.htm#use).

That says for commercial use, you need to contact him, and since hyperglot is in the rosettatype org, I personally would see it as inherently commercial. If it was under the @MrBrezina account it might be more plausibly argued as a personal and non-commercial project, but even then that could be debatable to me. NC licenses are a scourge on serious people! XD

**Comment by MrBrezina** [comment]
Apologies for the long silence. I needed to get some distance from this.

Re Omniglot: we did not contact the author behind Ominglot. I do not think we need a permission as we are not using their creative work. We report facts (alphabets etc.), we structure them (base/auxiliary/marks groups), and review/support them using references such as Alvestrand, Omniglot, Wikipedia etc. 

Think about it, you cannot copyright an alphabet!

And just to clarify, none of our data are mindless copies or data dumps.

As previously stated, we are happy to consider other licences that may be needed. Please, get in touch or open an issue about that.
